#!/bin/sh
set -e
case "$1" in
	configure|install)
		#keep this sudo here. For some odd reason, it doesn't work without it.
		sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/drauger-theme/drauger-theme.plymouth 100 --slave /usr/share/plymouth/themes/default.grub default.plymouth.grub /usr/share/plymouth/themes/drauger-theme/drauger-theme.grub
		sudo update-alternatives --install /usr/share/plymouth/themes/text.plymouth text.plymouth /usr/share/plymouth/themes/drauger-text/drauger-text.plymouth 100
		if which update-initramfs >/dev/null 2>&1; then
			update-initramfs -u
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure) ;;

	*)
		echo "$0 called with unknown argument \`$1'" >&2
		exit 1
	;;
esac
exit 0
